---
- name: Add search domains to network card
  ansible.builtin.nmcli:
    conn_name: "Wired connection 1"  # Change this to your actual connection name
    type: ethernet
    dns_search: "{{ domain_list | join(' ') }}"
  become: yes
