---
- name: Add search domains to network card
  ansible.builtin.nmcli:
    conn_name: "{{ adapter_name }}"  # Ensure this is the correct connection name
    type: ethernet
    dns4_search: "{{ domain_list | join(' ') }}"
  become: yes
