---
- name: Add search domains to network card
  ansible.builtin.nmcli:
    conn_name: "{{ adapter_name }}"  # Use the correct network connection name
    type: ethernet
    dns4_search: "{{ domain_list | join(' ') }}"
    state: present
  become: yes
