- name: Initialize nmcli failure flag
  set_fact:
    nmcli_failed: false

- name: Add search domains to network card
  ansible.builtin.nmcli:
    conn_name: "{{ adapter_name }}"  # Ensure this is set to the correct network adapter name
    type: ethernet
    dns4_search: "{{ domain_list | join(' ') }}"
    state: present
  register: nmcli_output  # Register the result of the nmcli command
  ignore_errors: true
  become: yes

- name: Set failure flag if nmcli command failed
  set_fact:
    nmcli_failed: true
  when: nmcli_output.failed

- name: Gather detailed network configuration
  command: nmcli -g IP4.ADDRESS,IP4.GATEWAY,IP4.DNS con show {{ nmcli_output.conn_name }}
  register: detailed_info

- name: Parse detailed network info
  set_fact:
    nmcli_output:
      Exists: "Connections do exist so we are modifying them"
      changed: true
      conn_name: "{{ adapter_name }}"
      failed: false
      state: 'present'
      details:
        ip_address: "{{ detailed_info.stdout_lines[0].split('/')[0] if detailed_info.stdout_lines | length > 0 else 'N/A' }}"
        gateway: "{{ detailed_info.stdout_lines[1] if detailed_info.stdout_lines | length > 1 else 'N/A' }}"
        dns_servers: "{{ detailed_info.stdout_lines[2].split(',') if detailed_info.stdout_lines | length > 2 else [] }}"

