- name: Add domain groups to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ item | regex_escape }} ALL=\\(ALL\\) ALL$'
    line: '"%{{ item }}" ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  loop: "{{ sudo_groups }}"
  register: sudo_groups_result
  ignore_errors: true
  become: yes

- name: Capture failure for groups
  set_fact:
    sudo_groups_failed: "Failed"
  when: sudo_groups_result is failed

- name: Add users to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '"{{ item }}" ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
    state: present
  loop: "{{ sudo_users }}"
  register: sudo_users_result
  ignore_errors: true
  become: yes

- name: Capture failure for users
  set_fact:
    sudo_users_failed: "Failed"
  when: sudo_users_result is failed
