- name: Add domain groups to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ item | regex_escape }} ALL=\\(ALL\\) ALL$'
    line: '"%{{ item }}" ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  loop: "{{ sudo_groups }}"
  register: sudo_groups_result
  become: yes

- name: Add users to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '"{{ item }}" ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
    state: present
  loop: "{{ sudo_users }}"
  register: sudo_users_result
  become: yes
