- name: Update access.conf with general security groups
  ansible.builtin.lineinfile:
    path: /etc/security/access.conf
    line: "+:({{ item }}):ALL"
    create: yes
    state: present
  loop: "{{ access_groups }}"
  register: access_groups_result
  become: yes

- name: Add users to access.conf
  ansible.builtin.lineinfile:
    path: /etc/security/access.conf
    line: "+:{{ item }}:ALL"
    state: present
  loop: "{{ access_users }}"
  register: access_users_result
  become: yes
