- name: Mount SMB share
  ansible.builtin.mount:
    path: /mnt/smb_share
    src: //10.203.20.3/Scripts/Reports
    fstype: cifs
    opts: "rw,guest"  # Changed to 'rw' for read-write access, and 'guest' if no auth is needed
    state: mounted

- name: Copy HTML report to SMB share
  ansible.builtin.copy:
    src: /tmp/my_html_report.html
    dest: /mnt/smb_share/my_html_report.html

- name: Unmount SMB share
  ansible.builtin.mount:
    path: /mnt/smb_share
    state: unmounted
