---
- name: Generate HTML report
  ansible.builtin.template:
    src: templates/html_email_report.j2
    dest: /tmp/my_html_report.html
  delegate_to: 10.203.20.199  # Ensure this runs on the remote host
