- name: Update PAM configurations to allow spaces in user and group names
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^(account\s+required\s+pam_access\.so)'
    line: '\1 listsep=,'
    backrefs: yes
  loop:
    - /etc/pam.d/atd
    - /etc/pam.d/crond
    - /etc/pam.d/password-auth
    - /etc/pam.d/system-auth
  ignore_errors: yes
  register: pam_update_results
  become: yes
