- name: Initialize PAM configuration failure flag
  set_fact:
    pam_update_failed: false

- name: Update PAM configurations to allow spaces in user and group names
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^(account\s+required\s+pam_access\.so)'
    line: '\1 listsep=,'
    backrefs: yes
  loop:
    - /etc/pam.d/atd
    - /etc/pam.d/crond
    - /etc/pam.d/password-auth
    - /etc/pam.d/system-auth
  ignore_errors: true
  register: pam_update_results

- name: Set failure flag if any PAM configuration update fails
  set_fact:
    pam_update_failed: "{{ pam_update_results.results | map(attribute='failed') | select('equalto', true) | list | length > 0 }}"
  when: pam_update_results.results is defined
