- name: Get current hostname
  ansible.builtin.setup:
    filter: ansible_hostname
  register: current_hostname

- name: Change the hostname only if needed
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"
  when: current_hostname.ansible_facts.ansible_hostname != new_hostname
  register: hostname_change_output
