- name: Set kernel limit in dnf.conf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^installonly_limit='
    line: "installonly_limit={{ kernel_limit }}"
    create: yes
  register: dnf_kernel_limit_result
  become: yes

- name: Set kernel limit in yum.conf
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    regexp: '^installonly_limit='
    line: "installonly_limit={{ kernel_limit }}"
    create: yes
  register: yum_kernel_limit_result
  become: yes
