- name: Get current hostname
  ansible.builtin.command:
    cmd: hostname
  register: current_hostname

- name: Change the hostname
  ansible.builtin.hostname:
    name: "{{ new_hostname | upper }}"
  register: hostname_change_output
  ignore_errors: true
  failed_when: hostname_change_output is failed

- name: Set default result if hostname change task resulted in no changes
  ansible.builtin.set_fact:
    hostname_change_output:
      skipped: true
      msg: "Hostname change was skipped as it is already set correctly."
  when: hostname_change_output is skipped or not hostname_change_output.changed
