- name: Initialize cron job failure flag
  set_fact:
    cron_job_failed: false

- name: Set nightly cron job
  ansible.builtin.cron:
    name: "Nightly Update Job"
    job: "{{ cron_command }}"
    hour: 0
    minute: 0
    user: "{{ cron_user | default('root') }}"
    state: present
  register: cron_job_result
  ignore_errors: true

- name: Set failure flag if cron job setup fails
  set_fact:
    cron_job_failed: true
  when: cron_job_result.failed
