---
- name: Change Hostname
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"
  register: hostname_change

- name: Check if hostname was changed
  fail:
    msg: "Hostname change failed."
  when: not hostname_change.changed
