- name: Update all packages
  dnf:
    name: '*'
    state: latest
    autoremove: yes
  register: update_result

- name: Check if a reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the machine if required
  reboot:
    msg: "Rebooting for system updates"
    connect_timeout: 5
    reboot_timeout: 600  # Increased timeout for servers that might take longer
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists

- name: Set update and reboot status
  set_fact:
    update_status: "Update and reboot completed successfully."
  when: update_result.changed or reboot_required.stat.exists

- name: Set update status only
  set_fact:
    update_status: "Update completed successfully, no reboot required."
  when: update_result.changed and not reboot_required.stat.exists

- name: Set no changes status
  set_fact:
    update_status: "No updates applied, system already up-to-date."
  when: not update_result.changed
