---
- name: Parent Playbook
  hosts: all
  gather_facts: yes

  tasks:
    - block:
        - name: Include Set Hostname Tasks
          include_tasks: tasks/set_hostname.yml
          
        - name: Update /etc/hosts File
          include_tasks: tasks/update_hosts.yml
          
        - name: Set Kernel Limit
          include_tasks: tasks/set_kernel_limit.yml

        - name: Set System Timezone to UTC
          include_tasks: tasks/set_timezone.yml

        - name: Add Search Domains to Network Card
          include_tasks: tasks/add_search_domains.yml

        - name: Ensure PAM files are configured for AD integration
          include_tasks: tasks/modify_pam_files.yml

        - name: Add Domain Groups to Sudoers
          include_tasks: tasks/add_domain_groups_sudoers.yml

        - name: Configure Access Control for Security Groups
          include_tasks: tasks/configure-access-control.yml

        - name: Include nightly cron job setup
          include_tasks: tasks/set_nightly_cron_job.yml
      
      rescue:
        - name: Set failure fact
          set_fact:
            task_status: "Failed"

    # - name: Send Confirmation Email
    #   community.general.mail:
    #     host: smtp.example.com
    #     port: 587
    #     username: ansible@example.com
    #     password: "{{ email_password }}"
    #     to: Admin <admin@example.com>
    #     subject: 'Hostname Change Report for {{ inventory_hostname }}'
    #     subtype: html
    #     body: "{{ lookup('template', 'templates/html_email_report.j2') }}"
    #   delegate_to: localhost
